name: npm test
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout
      - name: Install Node.js
        uses: actions/setup-node
      - name: Run npm install
        run: npm install