name: npm test
on: [push]
jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout
      - name : setup node
        uses: actions/setup-node
        with:
          node-version: 'lts/*'
      - name: run test
        run: npm install